import _IconFileAudio from './IconFileAudio';
export { _IconFileAudio as IconFileAudio };
import _IconFileBookmark from './IconFileBookmark';
export { _IconFileBookmark as IconFileBookmark };
import _IconFileBoxNote from './IconFileBoxNote';
export { _IconFileBoxNote as IconFileBoxNote };
import _IconFileCode from './IconFileCode';
export { _IconFileCode as IconFileCode };
import _IconFileDefault from './IconFileDefault';
export { _IconFileDefault as IconFileDefault };
import _IconFileDocument from './IconFileDocument';
export { _IconFileDocument as IconFileDocument };
import _IconFileIllustrator from './IconFileIllustrator';
export { _IconFileIllustrator as IconFileIllustrator };
import _IconFileImage from './IconFileImage';
export { _IconFileImage as IconFileImage };
import _IconFileIndesign from './IconFileIndesign';
export { _IconFileIndesign as IconFileIndesign };
import _IconFilePDF from './IconFilePDF';
export { _IconFilePDF as IconFilePDF };
import _IconFilePhotoshop from './IconFilePhotoshop';
export { _IconFilePhotoshop as IconFilePhotoshop };
import _IconFilePresentation from './IconFilePresentation';
export { _IconFilePresentation as IconFilePresentation };
import _IconFileSpreadsheet from './IconFileSpreadsheet';
export { _IconFileSpreadsheet as IconFileSpreadsheet };
import _IconFileText from './IconFileText';
export { _IconFileText as IconFileText };
import _IconFileThreeD from './IconFileThreeD';
export { _IconFileThreeD as IconFileThreeD };
import _IconFileVector from './IconFileVector';
export { _IconFileVector as IconFileVector };
import _IconFileVideo from './IconFileVideo';
export { _IconFileVideo as IconFileVideo };
import _IconFileZip from './IconFileZip';
export { _IconFileZip as IconFileZip };
import _default from './FileIcon';
export { _default as default };